#!/bin/bash
# SPDX-License-Identifier: MIT
#
# AfriyieOS — verify the package reader against real distribution archives
#
# Downloads a handful of genuine packages from a distribution's CDN and runs the
# reader over them, reporting what it makes of each.
#
# WHY THIS EXISTS, SEPARATELY FROM THE NATIVE TESTS
#
# tests/native runs against fixtures generated by tools/pkgsynth.py. Those
# fixtures are real containers — `ar`, `gzip -t` and `tar` all accept them — but
# they are still OUR IDEA of what a package looks like, and a fixture written
# from a misunderstanding agrees with code written from the same misunderstanding.
#
# That is not a hypothetical. Every fixture passed while the Alpine reader
# treated each gzip member as its own tar; a real package from Alpine's CDN
# disproved it, because a real .apk is ONE tar split across members at arbitrary
# offsets. A second real package then carried .post-install, .post-upgrade and
# .trigger, which the reader offered as files to install.
#
# Both bugs were found within minutes of pointing the reader at reality, after
# weeks of green fixtures. So this script is part of the test suite, not a
# curiosity.
#
# The packages are NOT committed: they are megabytes each, they change without
# notice, and redistributing them is not this repository's business. They are
# downloaded into build/ and discarded with it.
#
# Usage:
#   ./tools/realpackages.sh              # Alpine, the default
#   ./tools/realpackages.sh --keep       # leave the downloads in place
#
# Exit status is 0 when every package was read, 2 when there was no network —
# a missing network is not a test failure, and treating it as one would make the
# gate flaky for a reason that has nothing to do with the code.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || exit 1

ALPINE_BASE="https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64"
DEST="build/realpkgs"

# Chosen for different shapes rather than for being popular: a C library, a
# compressor, a shell with install scripts, a data-only package with many files,
# and one with five dependencies.
PACKAGES="musl zlib busybox ncurses-terminfo-base ca-certificates"

mkdir -p "$DEST" build

# --- is there a network at all? ---------------------------------------------
if ! curl -sS --max-time 15 -o /dev/null "$ALPINE_BASE/" 2>/dev/null; then
    echo "no network — skipping real-package verification"
    exit 2
fi

curl -sS --max-time 30 "$ALPINE_BASE/" -o "$DEST/index.html" || exit 2

# Take exact filenames from the index. Guessing a version produces a download
# failure that looks like a reader failure, which is a waste of an afternoon.
pick() {
    grep -oE "href=\"$1-[0-9][^\"]*\.apk\"" "$DEST/index.html" \
        | sed 's/href="//; s/"//' \
        | grep -vE -- '-(doc|dev|dbg|static|openrc|bash|extras)$' \
        | head -1
}

echo "=== fetching real packages ==="
for base in $PACKAGES; do
    name=$(pick "$base")
    if [ -z "$name" ]; then
        echo "  no package named $base in the index"
        continue
    fi
    if [ -f "$DEST/$name" ]; then
        printf '  have %s\n' "$name"
        continue
    fi
    if curl -sS --max-time 90 -f "$ALPINE_BASE/$name" -o "$DEST/$name" 2>/dev/null; then
        printf '  got  %-44s %s bytes\n' "$name" "$(stat -c%s "$DEST/$name")"
    else
        printf '  miss %s\n' "$name"
        rm -f "$DEST/$name"
    fi
done

# --- the probe ---------------------------------------------------------------
cat > build/realprobe.c <<'EOF'
#include "afpkg.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static unsigned char scratch[64 * 1024 * 1024];

int main(int argc, char **argv)
{
    FILE *file = fopen(argv[1], "rb");
    if (file == NULL) { printf("  cannot open %s\n", argv[1]); return 1; }
    fseek(file, 0, SEEK_END);
    long size = ftell(file);
    fseek(file, 0, SEEK_SET);
    unsigned char *buf = malloc((size_t)size);
    if (fread(buf, 1, (size_t)size, file) != (size_t)size) { fclose(file); return 1; }
    fclose(file);

    afpkg_scratch_t s;
    s.base = scratch;
    s.size = sizeof(scratch);

    af_pkg_t pkg;
    if (afpkg_open(buf, (af_size)size, &s, &pkg) != AF_OK) {
        printf("  FAIL  %-44s %s\n", argv[1], afpkg_error(&pkg));
        free(buf);
        return 1;
    }

    afpkg_iter_t it;
    afpkg_iter_begin(&it);
    af_pkg_entry_t e;
    int files = 0, dirs = 0, leaked = 0;

    while (afpkg_iter_next(&pkg, &it, &e)) {
        if (e.is_directory) { dirs++; } else { files++; }
        /* A dot-name at the root is metadata. Finding one here means an
           installer would write a file called ".post-install" into the user's
           root directory. */
        if (e.path[0] == '.' && strchr(e.path, '/') == NULL) { leaked++; }
    }

    printf("  ok    %-24s %-16s %-9s %3d files %3d dirs  deps %2u  leaked %d\n",
           pkg.info.name, pkg.info.version, pkg.info.architecture,
           files, dirs, pkg.info.depends_count, leaked);

    free(buf);
    return leaked == 0 ? 0 : 1;
}
EOF

gcc -std=gnu11 -w -Ikernel/include -Ilibs/libafpkg/include \
    libs/libafpkg/afpkg.c libs/libafpkg/inflate.c build/realprobe.c \
    -o build/realprobe || { echo "probe failed to build"; exit 1; }

echo
echo "=== the reader against real Alpine packages ==="
pass=0
fail=0
for pkg in "$DEST"/*.apk; do
    [ -f "$pkg" ] || continue
    if ./build/realprobe "$pkg"; then pass=$((pass + 1)); else fail=$((fail + 1)); fi
done

echo
if [ "$fail" -eq 0 ]; then
    printf '  %d real package(s) read, none leaked metadata\n' "$pass"
    exit 0
fi

printf '  %d passed, %d FAILED\n' "$pass" "$fail"
exit 1
